//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGroceryStore4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.purchaseDetails = new HashSet<purchaseDetail>();
        }
    
        public int pro_id { get; set; }
        [Required(ErrorMessage = "Product Name is required.")]
        [Display(Name = "Product Name")]
        public string pro_name { get; set; }

        [Required(ErrorMessage = "Barcode is required.")]
        [StringLength(11, MinimumLength = 11)]
        [Display(Name = "Barcode")]
        public string pro_barcode { get; set; }

        [Display(Name = "Location")]
        [RegularExpression(@"^[A-Z]-\d\d-[A-Z]-\d\d$", ErrorMessage="Please Enter the location in AA-01-AA-02 format")]
        public string pro_location { get; set; }

        [Required(ErrorMessage = "Quantity is required")]
        [Display(Name = "Quantity")]
        public int pro_quantity { get; set; }

        [Display(Name = "Description")]
        public string p_description { get; set; }

        [Display(Name = "Price")]
        public Nullable<decimal> p_price { get; set; }

        [Display(Name = "Category")]
        public Nullable<int> pro_catID { get; set; }

        [Display(Name = "Image")]
        public string pro_image { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchaseDetail> purchaseDetails { get; set; }
        public virtual category category { get; set; }
    }
}
