//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGroceryStore4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class purchaseDetail
    {
        public long pd_id { get; set; }
        [Required(ErrorMessage = "Purchase is required.")]
        [Display(Name = "Purchase")]
        public long pd_purchaseId { get; set; }

        [Required(ErrorMessage = "Product is required.")]
        [Display(Name = "Product")]
        public int pd_proId { get; set; }

        [Required(ErrorMessage = "Quantity is required.")]
        [Display(Name = "Quantity")]
        public int pd_quantity { get; set; }

        [Required(ErrorMessage = "Buying Price is required.")]
        [Display(Name = "Buying Price")]
        public decimal pd_buyingPrice { get; set; }


        public virtual purchase purchase { get; set; }
        public virtual product product { get; set; }
    }
}
