//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGroceryStore4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.purchases = new HashSet<purchase>();
        }
    
        public int sup_id { get; set; }
        [Required(ErrorMessage = "Supplier Name is required.")]
        [Display(Name = "Supplier Name")]
        public string sup_name { get; set; }
        [Required(ErrorMessage = "Supplier Address is required.")]
        [Display(Name = "Supplier Address")]
        public string sup_address { get; set; }

        [Required(ErrorMessage = "Phone is required.")]
        [StringLength(10, MinimumLength = 10)]
        [Display(Name = "Phone Number")]
        public string sup_phone { get; set; }

        [Display(Name = "Balance")]
        public Nullable<int> sup_balance { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase> purchases { get; set; }
    }
}
